### ISSUE TITLE
Publish cereal header file generator

### ISSUE THREAD

**Issue by ncoghlan** [tritiumdev/cereal-ocpp2#1]
@wolfwoolford wrote a code generator to convert the Open Charge Alliance's OCPP 2.0 JSON schema definitions to cereal class definitions for C++.

We're going to publish that here under LGPLv3+

**Comment by wolfwoolford** [comment]
Nick, wow, thanks to you and everyone at Tritium! Happy days I am over the moon. I look forward to any opportunities to contribute and collaborate with you guys on this library, or the world at large!

**Comment by ncoghlan** [comment]
Generator code has been published: https://github.com/tritiumdev/cereal-ocpp2/commit/e8cef7e59e4942af453fc32fb2106629f75ce67a
As well as the source OCA schemas: https://github.com/tritiumdev/cereal-ocpp2/commit/5bb1104ceb00095931b6b5869b73d6a2cc17365b
